"""
Stage 2 (real): semantic enrichment via LLM.

This file uses LangChain and the build_llm() helper to keep a single flexible configuration point
for provider/model selection (Groq, Ollama, etc.) without mixing Anthropic's direct API with the
LangChain tool-calling interface.
"""
import json
import os
import sqlite3
import sys
from pathlib import Path

from langchain_core.tools import tool

if __package__ in (None, ""):
    project_root = Path(__file__).resolve().parent.parent
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

from src.project_paths import resolve_artifact_path, resolve_db_path


def build_llm(provider: str = "groq", model_name: str = "openai/gpt-oss-20b"):
    """Single configuration point for provider/model selection."""
    if provider == "groq":
        from langchain_groq import ChatGroq
        resolved_key = os.getenv("GROQ_API_KEY")
        if not resolved_key:
            raise RuntimeError(
                "Missing GROQ_API_KEY. Export the variable before running this script:\n"
                "  export GROQ_API_KEY='your_key_here'\n"
                "  python3 src/enrich_with_LLM_langchain.py"
            )
        return ChatGroq(model=model_name, temperature=0, api_key=resolved_key)
    if provider == "ollama":
        from langchain_ollama import ChatOllama
        return ChatOllama(model=model_name, temperature=0)
    raise ValueError(f"Unknown provider: {provider}")


@tool
def describe_table(
    table_name: str,
    columns: list,
    foreign_keys: list,
    sample_rows: list,
) -> dict:
    """Generates a semantic description for a given table."""
    return {
        "table_name": table_name,
        "table_description": "Description generated by the model",
        "column_descriptions": {},
        "example_questions": [],
    }


@tool
def describe_full_schema(tables: list) -> dict:
    """Generates the semantic description for all tables in the schema."""
    return {"tables": tables}


def get_sample_rows(db_path: str, table: str, n: int = 3) -> list:
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM '{table}' LIMIT {n}")
    cols = [d[0] for d in cur.description]
    rows = [dict(zip(cols, row)) for row in cur.fetchall()]
    conn.close()
    return rows


def enrich_table_with_llm(table_name: str, table_info: dict, sample_rows: list, llm=None) -> dict:
    llm = llm or build_llm()
    prompt = f"""Analyze this database table and generate its semantic documentation.

Table: {table_name}
Columns: {json.dumps(table_info['columns'], ensure_ascii=False)}
Relationships (foreign keys): {json.dumps(table_info['foreign_keys'], ensure_ascii=False)}
Sample rows:
{json.dumps(sample_rows, ensure_ascii=False, indent=2)}

IMPORTANT: if this table could be confused with a similar table in the same domain, include in
`table_description` what clearly distinguishes it.
Do not repeat the same keyword in example_questions for different tables unless it is genuinely
specific to that table — avoid generic phrases that could apply to any table in the domain."""

    model = llm.bind_tools([describe_table])
    response = model.invoke(prompt)

    if getattr(response, "tool_calls", None):
        args = response.tool_calls[0]["args"]
        return {
            "table_name": table_name,
            "table_description": args.get("table_description", ""),
            "column_descriptions": args.get("column_descriptions", {}),
            "example_questions": args.get("example_questions", []),
        }

    if isinstance(response.content, str):
        try:
            parsed = json.loads(response.content)
            if isinstance(parsed, dict):
                return {
                    "table_name": table_name,
                    "table_description": parsed.get("table_description", ""),
                    "column_descriptions": parsed.get("column_descriptions", {}),
                    "example_questions": parsed.get("example_questions", []),
                }
        except Exception:
            pass

    raise RuntimeError(f"The model did not return a usable response for {table_name}")


def enrich_all_at_once(
    catalog: dict,
    db_path: str,
    provider: str = "groq",
    model_name: str = "openai/gpt-oss-20b",
) -> dict:
    """Generates and returns descriptions for all tables using LangChain + tool calling."""
    llm = build_llm(provider=provider, model_name=model_name)
    model = llm.bind_tools([describe_full_schema])

    schema_overview = []
    for table_name, info in catalog.items():
        schema_overview.append({
            "table": table_name,
            "columns": info["columns"],
            "foreign_keys": info["foreign_keys"],
            "sample_rows": get_sample_rows(db_path, table_name, n=2),
        })

    prompt = f"""Analyze this complete database schema and generate the semantic
documentation for each table.

Full schema ({len(schema_overview)} tables):
{json.dumps(schema_overview, ensure_ascii=False, indent=2)}

CRITICAL INSTRUCTIONS:
- You have visibility of all tables at once. Use it: if two tables could be confused with each other,
  the description of each one must explicitly state what distinguishes it from the other.
- The example questions for one table must not reuse keywords that are equally common in another
  table's example questions.
- Generate output for the {len(schema_overview)} tables in the same order they appear above."""

    response = model.invoke(prompt)

    if getattr(response, "tool_calls", None):
        tool_args = response.tool_calls[0]["args"]
        results = tool_args.get("tables", [])
    else:
        content = response.content if hasattr(response, "content") else str(response)
        try:
            payload = json.loads(content)
            results = payload.get("tables", [])
        except Exception as exc:
            raise RuntimeError(f"The model did not return a usable tool-call JSON: {exc}") from exc

    results_by_table = {item["table_name"]: item for item in results}

    for table_name, table_info in catalog.items():
        result = results_by_table.get(table_name)
        if not result:
            print(f"  WARNING: the LLM did not generate a description for {table_name}")
            continue
        table_info["description"] = result["table_description"]
        table_info["example_questions"] = result.get("example_questions", [])
        table_info["status"] = "pending_review"
        col_descs = result.get("column_descriptions", {})
        for col in table_info["columns"]:
            if col["name"] in col_descs:
                col["description"] = col_descs[col["name"]]

    return catalog


def approve_all(catalog: dict) -> dict:
    for table_info in catalog.values():
        table_info["status"] = "active"
    return catalog


if __name__ == "__main__":
    try:
        input_path = resolve_artifact_path("catalog_raw.json")
        db_path = resolve_db_path("chinook.db")
        output_path = resolve_artifact_path("catalog_enriched_llm.json")

        with open(input_path, encoding="utf-8") as f:
            catalog = json.load(f)

        catalog = enrich_all_at_once(catalog, str(db_path))

        print("\n" + "=" * 70)
        print("GENERATED DESCRIPTIONS (pending_review) — review them before approving")
        print("=" * 70)
        for t, info in catalog.items():
            print(f"\n[{info['status']}] {t}")
            print(f"  Description: {info['description']}")
            print(f"  Example questions: {info['example_questions']}")

        response = input("\nApprove all and save? (y/n): ")
        if response.lower() == "y":
            catalog = approve_all(catalog)
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(catalog, f, indent=2, ensure_ascii=False)
            print(f"Saved -> {output_path}")
        else:
            print("Not saved. Adjust the prompt and rerun.")
    except RuntimeError as exc:
        print(f"\nERROR: {exc}")
        raise SystemExit(1)