"""
Stage 2: semantic enrichment.

In production, this step calls an LLM for each ambiguous table/column, using the name,
type, and a sample of anonymized rows. The result enters a `pending_review` queue until a
human approves it (see the architecture proposal, section "Light semantic layer").

For this MVP, with only 11 tables, the descriptions were written by reasoning directly from
the schema and a real sample of rows (see the conversation) — fulfilling the same role the
LLM call would play in production. They are marked as `pending_review` and then "approved"
through `approve_all()` to simulate that flow step.
"""
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    project_root = Path(__file__).resolve().parent.parent
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

from src.project_paths import resolve_artifact_path

# Semantic descriptions by table and ambiguous column.
# This dictionary is the output that the Enricher agent (LLM) would generate in production,
# one table at a time.
DESCRIPTIONS = {
    "Artist": {
        "table": "Musical artists or bands. Only the artist name, without albums or songs directly.",
        "columns": {},
        "example_questions": [
            "Which artists have more than 5 albums?",
            "Which artists are the most popular?",
        ],
    },
    "Album": {
        "table": "Music albums, each belonging to a single artist. It does not contain songs themselves, only the album title.",
        "columns": {},
        "example_questions": [
            "How many albums does each artist have?",
            "Which album has the most songs?",
        ],
    },
    "Track": {
        "table": "Individual songs available for sale, each belonging to an album, with a genre and audio format.",
        "columns": {
            "Milliseconds": "Song duration in milliseconds",
            "UnitPrice": "Sale price of the individual song",
            "Composer": "Name of the song's composer",
        },
        "example_questions": [
            "Which songs are the longest?",
            "Which song is the most expensive?",
            "Who composed this song?",
        ],
    },
    "Genre": {
        "table": "Music genres (Rock, Jazz, Classical, etc.), used to classify songs. It does not contain sales information.",
        "columns": {},
        "example_questions": [
            "Which genres are the most popular?",
            "How many songs are there in each genre?",
        ],
    },
    "MediaType": {
        "table": "Technical audio file format for a song (MPEG, AAC, etc.), not related to price or sales.",
        "columns": {},
        "example_questions": [
            "How many songs are there for each audio format type?",
            "Which file formats are used?",
        ],
    },
    "Playlist": {
        "table": "User-created playlists that group songs. Only the playlist name, not the songs it contains.",
        "columns": {},
        "example_questions": [
            "How many playlists exist?",
            "What is the name of each playlist?",
        ],
    },
    "PlaylistTrack": {
        "table": "Join table that associates songs with playlists (many-to-many relationship between Playlist and Track). Needed to know which songs each playlist contains.",
        "columns": {},
        "example_questions": [
            "List the songs from the largest playlist",
            "How many playlists include this song?",
        ],
    },
    "Customer": {
        "table": "External customers who buy music (they are not company employees). Includes contact details and the assigned support employee.",
        "columns": {
            "SupportRepId": "Support employee assigned to this customer",
        },
        "example_questions": [
            "Which customer has spent the most in total?",
            "In which country do most customers live?",
        ],
    },
    "Employee": {
        "table": "Internal company employees (not customers). Includes support representatives and their reporting hierarchy.",
        "columns": {
            "ReportsTo": "Employee ID of the direct manager for this employee",
            "Title": "Employee title or role",
        },
        "example_questions": [
            "Which employee has the most assigned customers?",
            "Who is the direct manager of each employee?",
        ],
    },
    "Invoice": {
        "table": "Purchase invoices generated by a customer, with TOTAL amount and date. It does not include the details of which songs were purchased (that is in InvoiceLine).",
        "columns": {
            "Total": "Total invoice amount",
        },
        "example_questions": [
            "What is the total invoiced amount by country?",
            "How many invoices were generated last month?",
        ],
    },
    "InvoiceLine": {
        "table": "Line-by-line detail of which specific song was sold, at what price, and in what quantity, within an invoice. This is the key table for questions about sold songs, product revenue, or sales by genre.",
        "columns": {
            "UnitPrice": "Unit price of the song at the time of purchase",
            "Quantity": "Quantity purchased for that song in that line",
        },
        "example_questions": [
            "Which songs are the best sellers?",
            "Which genre has the most songs sold?",
            "How many units were sold of each product?",
        ],
    },
}


def enrich(catalog: dict) -> dict:
    for table_name, table_info in catalog.items():
        desc = DESCRIPTIONS.get(table_name, {})
        table_info["description"] = desc.get("table", f"Table {table_name} (without generated description)")
        table_info["example_questions"] = desc.get("example_questions", [])
        table_info["status"] = "pending_review"
        col_descs = desc.get("columns", {})
        for col in table_info["columns"]:
            if col["name"] in col_descs:
                col["description"] = col_descs[col["name"]]
    return catalog


def approve_all(catalog: dict) -> dict:
    """Simulates human approval of the review queue (PR/merge step)."""
    for table_info in catalog.values():
        table_info["status"] = "active"
    return catalog


if __name__ == "__main__":
    input_path = resolve_artifact_path("catalog_raw.json")
    output_path = resolve_artifact_path("catalog_enriched.json")

    with open(input_path, encoding="utf-8") as f:
        catalog = json.load(f)

    catalog = enrich(catalog)
    print("Generated descriptions (pending_review):")
    for t, info in catalog.items():
        print(f"  [{info['status']}] {t}: {info['description']}")

    catalog = approve_all(catalog)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, indent=2, ensure_ascii=False)
    print(f"\nCatalog enriched and approved -> {output_path}")